"""Database package for local storage."""

from mailklient.database.connection import connect, initialize_database
from mailklient.database.repositories import (
    create_account,
    create_folder,
    create_message,
    count_messages_for_folder,
    delete_account,
    delete_message,
    delete_messages_missing_from_folder,
    get_account,
    get_folder,
    get_folder_by_name,
    get_folder_last_seen_uid,
    get_attachment_content,
    get_message,
    list_attachments_for_message,
    list_accounts,
    list_folders,
    list_messages_for_folder,
    list_unified_inbox_messages,
    mark_message_read,
    move_message_to_folder,
    replace_message_attachments,
    set_attachment_content,
    update_account,
    update_folder_last_seen_uid,
    update_folder_remote_id,
    update_message_flags,
    upsert_message,
)

__all__ = [
    "connect",
    "create_account",
    "create_folder",
    "create_message",
    "count_messages_for_folder",
    "delete_account",
    "delete_message",
    "delete_messages_missing_from_folder",
    "get_account",
    "get_folder",
    "get_folder_by_name",
    "get_folder_last_seen_uid",
    "get_attachment_content",
    "get_message",
    "initialize_database",
    "list_attachments_for_message",
    "list_accounts",
    "list_folders",
    "list_messages_for_folder",
    "list_unified_inbox_messages",
    "mark_message_read",
    "move_message_to_folder",
    "replace_message_attachments",
    "set_attachment_content",
    "update_account",
    "update_folder_last_seen_uid",
    "update_folder_remote_id",
    "update_message_flags",
    "upsert_message",
]
